[project]
name = "comfyui-llm-prompt-enhancer"
description = "A ComfyUI node for enhancing prompts using any OpenAI-compatible LLM API"
version = "3.0.0"
license = {file = "LICENSE"}
dependencies = ["aiohttp>=3.9.0"]

[project.urls]
Repository = "https://github.com/pinkpixel-dev/comfyui-llm-prompt-enhancer"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pinkpixel-dev"
DisplayName = "ComfyUI LLM Prompt Enhancer"
Icon = "https://res.cloudinary.com/di7ctlowx/image/upload/v1738065925/promptenhancelogo_kql6qa.svg"
